namespace Long.Network.Packets
{
    /// <summary>
    ///     Packet types for the Conquer Online game client across all server projects.
    ///     Identifies packets by an unsigned short from offset 2 of every packet sent to
    ///     the server.
    /// </summary>
    public enum PacketType : ushort
    {
        MsgRegister = 1001,
        MsgTalk = 1004,
        MsgUserInfo = 1006,
        MsgItemInfo = 1008,
        MsgItem = 1009,
        MsgAction = 1010,
        MsgPlayer = 1014,
        MsgTick = 1012,
        MsgName = 1015,
        MsgWeather,
        MsgUserAttrib = 1017,
        MsgFriend = 1019,
        MsgQuiz = 1021,
        MsgInteract = 1022,
        MsgTeam = 1023,
        MsgAllot = 1024,
        MsgWeaponSkill = 1025,
        MsgTeamMember = 1026,
        MsgGemEmbed = 1027,
        MsgStatistic = 1028,
        MsgTeamAward = 1029,
        MsgAction2 = 1032,
        MsgData = 1033,
        MsgSchoolMemberPos = 1034,
        MsgGodExp = 1036,
        MsgPing = 1037,
        MsgSchoolMemberContrib = 1038,
        MsgSchoolMemberHis = 1039,
        MsgOfficial = 1040,
        MsgEnemyList = 1041,
        MsgMonsterTransform = 1042,
        MsgTeamRoll = 1043,
        MsgLoadMap = 1044,
        MsgMailOperation = 1045,
        MsgMailList = 1046,
        MsgMailNotify = 1047,
        MsgMailContent = 1048,
        MsgTrade = 1056,
        MsgConnect = 1052,
        MsgPlayerRestore = 1053,
        MsgConnectEx = 1055,
        MsgSynpOffer = 1058,
        MsgEncryptCode = 1059,
        MsgDutyMinContri = 1061,
        MsgSelfSynMemAwardRank = 1063,
        MsgSponsor = 1065,
        MsgMeteSpecial = 1066,
        MsgHangUp = 1070,
        MsgCompeteRank = 1071,
        MsgCampFight = 1072,
        MsgCampInfo = 1073,
        MsgCheatingProgram = 1081,
        MsgPCNum = 1100,
        MsgMapItem = 1101,
        MsgPackage = 1102,
        MsgMagicInfo = 1103,
        MsgFlushExp = 1104,
        MsgMagicEffect = 1105,
        MsgSyndicateAttributeInfo = 1106,
        MsgSyndicate = 1107,
        MsgItemInfoEx = 1108,
        MsgNpcInfoEx = 1109,
        MsgMapInfo = 1110,
        MsgMessageBoard = 1111,
        MsgSynMemberInfo = 1112,
        MsgDice = 1113,
        MsgSyndicateInfo = 1114,
        MsgEudemonInfo = 1116,
        MsgPackageBroodery = 1117,
        MsgTeamInfo = 1122,
        MsgEscapeKey = 1123,
        MsgTeamAction = 1124,
        MsgTeamMemberPos = 1125,
        MsgVipUserHandle = 1128,
        MsgBoothRequest = 1129,
        MsgTitle = 1130,
        MsgGhostGemPack = 1142,
        MsgAccount = 1060,
        MsgNpcInfo = 2030,
        MsgNpc = 2031,
        MsgTaskDialog = 2032,
        MsgFriendInfo = 2033,
        MsgTime = 2034,
        MsgPetInfo = 2035,
        MsgDataArray = 2036,
        MsgEudemonAttrib = 2037,
        MsgPlayerTask = 2039,
        MsgTaskList = 2040,
        MsgAnnounceList = 2041,
        MsgAnnounceInfo = 2042,
        MsgAuction = 2043,
        MsgTraining = 2044,
        MsgItemAttrib = 2045,
        MsgTradeBuddy = 2059,
        MsgWalkEx = 3005,

        // Account server packets
        MsgLoginStart = 30000,
        MsgLoginRealmAuth,
        MsgLoginRealmAuthEx,
        MsgLoginUserExchange,
        MsgLoginUserExchangeEx,
        MsgLoginAction,
        MsgLoginInformation,
        MsgLoginPlayerExchange,
        MsgLoginPlayerStatus,
        MsgLoginCmd,
        MsgLoginPing,
        MsgLoginGameInformation,
        MsgLoginUserError,
        MsgLoginEnd = 30999,

        // NPC Server packets
        MsgAiServerStart = 31000,
        MsgAiLoginExchange,
        MsgAiLoginExchangeEx,
        MsgAiPing,
        MsgAiAction,
        MsgAiSpawnNpc,
        MsgAiPlayerLogin,
        MsgAiPlayerLogout,
        MsgAiRoleStatusFlag,
        MsgAiGeneratorManage,
        MsgAiDynaMap,
        MsgAiRoleLogin,
        MsgAiRoleLogout,
        MsgAiInteract,
        MsgAiServerEnd = 31999,

        MsgUpdStart = 32000,
        MsgUpdQueryVersion,
        MsgUpdPatchList,
        MsgUpdCheckHash,
        MsgUpdConfirmHash,
        MsgUpdPing,
        MsgUpdEnd = 32999,

        /*
         * Piglet is GM Service!
         * Those messages generate interaction between the GM Panel in the web interface and
         * the game servers. Packets are shared between Game <-> Piglet <-> GM Panel
         */ 
        MsgPigletStart = 33000,
        MsgPigletPing,
        MsgPigletUserBan,
        MsgPigletUserMail,
        MsgPigletUserMassMail,
        MsgPigletUserLogin,
        MsgPigletItemSuspicious,
        MsgPigletUserCount, 
        MsgPigletRealmStatus,
        MsgPigletRealmAnnounceMaintenance,
        MsgPigletUserCreditInfo,
        MsgPigletUserCreditInfoEx,
        MsgPigletRealmUpdateCheck,
        MsgPigletClaimFirstCredit,
        MsgPigletLogOutputRedirect,
        MsgPigletShutdown,
        MsgPigletRealmAction,
        MsgPigletEnd = 33999,
        
        MsgDiscordStart = 34000,
        MsgDiscordEnd = 34999,

        MsgLongHandshake = 40001,
        MsgLongLogin,
        MsgLongLoginEx,

        MsgLongAntiCheatStart = 35000,
        MsgLongAntiCheatAddClient,
        MsgLongAntiCheatCheckClient,
        MsgLongAntiCheatChangeConnectionId,
        MsgLongAntiCheatProcessWarning,
        MsgLongAntiCheatProcessList,
    }
}
